version: '3'
services:
  api:
    build: .
    expose:
      - "8180"
    ports:
      - "8180:8180"
    volumes:
      - "./bin:/code/bin"
      - "./cfg:/code/cfg"
    environment:
        DEBUG_MODE: "true"
